version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: crm-postgres
    environment:
      POSTGRES_DB: crm_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crm-network

volumes:
  postgres_data:

networks:
  crm-network:
    driver: bridge
